/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus.ui;

import perpus.ui.admin.HakAkses;
import perpus.ui.master.MasterAnggota;
import perpus.ui.master.MasterBuku;
import perpus.ui.master.MasterPegawai;

/**
 *
 * @author martinusadyh
 */
public class MainForm extends javax.swing.JFrame {
    
    private Integer indexTab = -1;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnItemPegawai = new javax.swing.JMenuItem();
        mnItemAnggota = new javax.swing.JMenuItem();
        mnItemBuku = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan v0.1");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem6.setText("Login");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Logout");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Themes");
        jMenuBar1.add(jMenu6);

        jMenu2.setText("Master");

        mnItemPegawai.setText("Entri Pegawai");
        mnItemPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemPegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(mnItemPegawai);

        mnItemAnggota.setText("Entri Anggota");
        mnItemAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAnggotaActionPerformed(evt);
            }
        });
        jMenu2.add(mnItemAnggota);

        mnItemBuku.setText("Entri Buku");
        mnItemBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemBukuActionPerformed(evt);
            }
        });
        jMenu2.add(mnItemBuku);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Admin");

        jMenuItem1.setText("Konfigurasi Denda");
        jMenu5.add(jMenuItem1);

        jMenu7.setText("User Managemen");

        jMenuItem5.setText("Hak Akses");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItem4.setText("Grup Akses");
        jMenu7.add(jMenuItem4);

        jMenu5.add(jMenu7);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Laporan");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemPegawaiActionPerformed
        MasterPegawai.getPanel().setName(MasterPegawai.PANEL_NAME);
        indexTab = getComponentIndexByName(MasterPegawai.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(MasterPegawai.PANEL_NAME, MasterPegawai.getPanel());
            setSelectedPanel(MasterPegawai.PANEL_NAME);
        } else {
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnItemPegawaiActionPerformed

    private void mnItemAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAnggotaActionPerformed
        MasterAnggota.getPanel().setName(MasterAnggota.PANEL_NAME);
        indexTab = getComponentIndexByName(MasterAnggota.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(MasterAnggota.PANEL_NAME, MasterAnggota.getPanel());
            setSelectedPanel(MasterAnggota.PANEL_NAME);
        } else {
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnItemAnggotaActionPerformed

    private void mnItemBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemBukuActionPerformed
        MasterBuku.getPanel().setName(MasterBuku.PANEL_NAME);
        indexTab = getComponentIndexByName(MasterBuku.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(MasterBuku.PANEL_NAME, MasterBuku.getPanel());
            setSelectedPanel(MasterBuku.PANEL_NAME);
        } else {
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_mnItemBukuActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        HakAkses.getPanel().setName(HakAkses.PANEL_NAME);
        indexTab = getComponentIndexByName(HakAkses.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(HakAkses.PANEL_NAME, HakAkses.getPanel());
            setSelectedPanel(HakAkses.PANEL_NAME);
        } else {
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private int getComponentIndexByName(String panelName) {
        return mainTabbedPane.indexOfTab(panelName);
    }
    
    private void setSelectedPanel(String panelName) {
        mainTabbedPane.setSelectedComponent(mainTabbedPane.getComponentAt(getComponentIndexByName(panelName)));
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainForm().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JMenuItem mnItemAnggota;
    private javax.swing.JMenuItem mnItemBuku;
    private javax.swing.JMenuItem mnItemPegawai;
    // End of variables declaration//GEN-END:variables
}
