/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormKonfigurasi.java
 *
 * Created on Oct 10, 2012, 5:12:06 PM
 */
package perpus.ui.admin;

import javax.swing.JOptionPane;
import org.springframework.util.StringUtils;
import perpus.Main;
import perpus.domain.Konfigurasi;
import perpus.util.TextComponentUtils;

/**
 *
 * @author adi
 */
public class FormKonfigurasi extends javax.swing.JPanel {

    public static final String PANEL_NAME = "Konfigurasi Denda";
    private static FormKonfigurasi panel;
    private Konfigurasi konfig;

    public static FormKonfigurasi getPanel() {
        if(panel==null){
            panel = new FormKonfigurasi();
        }
        return panel;
    }
    
    /** Creates new form FormKonfigurasi */
    public FormKonfigurasi() {
        initComponents();
        TextComponentUtils.setCurrency(txtDenda);
        TextComponentUtils.setNumericTextOnly(txtMaxLamaPinjam);
        konfig = Main.getMasterService().getKonfigurasi();
        defaultForm();
    }
    
    void loadFormToDomain(){
        if(konfig==null){
            konfig = new Konfigurasi();
        }
        konfig.setDendaPerHari(TextComponentUtils.parseNumberToBigDecimal(txtDenda.getText()));
        konfig.setMaxLamaPinjam(Integer.parseInt(txtMaxLamaPinjam.getText()));
    }
    
    void loadDomainToForm(){
        txtDenda.setText(TextComponentUtils.formatNumber(konfig.getDendaPerHari()));
        txtMaxLamaPinjam.setText(konfig.getMaxLamaPinjam().toString());
    }
    
    void enableForm(Boolean status){
        txtDenda.setEnabled(status);
        txtMaxLamaPinjam.setEnabled(status);
    }
    
    void defaultForm(){
        loadDomainToForm();
        enableForm(false);
        statusButton(Boolean.TRUE, Boolean.FALSE, Boolean.FALSE);
    }
    
    void editForm(){
        enableForm(true);
        statusButton(Boolean.FALSE, Boolean.TRUE, Boolean.TRUE);
    }
    
    void statusButton(Boolean edit, Boolean save, Boolean cancel){
        btnEdit.setEnabled(edit);
        btnSimpan.setEnabled(save);
        btnBatal.setEnabled(cancel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtMaxLamaPinjam = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();

        jLabel1.setText("Max Lama Pinjam");

        jLabel2.setText("Denda per Hari");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpus/img/edit.gif"))); // NOI18N
        btnEdit.setToolTipText("Edit Konfigurasi");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpus/img/save.png"))); // NOI18N
        btnSimpan.setToolTipText("Simpan Konfigurasi");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpus/img/reload.png"))); // NOI18N
        btnBatal.setToolTipText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMaxLamaPinjam)
                    .addComponent(txtDenda))
                .addGap(54, 54, 54))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnEdit, btnSimpan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBatal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaxLamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit)
                            .addComponent(btnSimpan))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnEdit, btnSimpan, jLabel1, jLabel2, txtDenda, txtMaxLamaPinjam});

    }// </editor-fold>//GEN-END:initComponents

    private void txtDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDendaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(StringUtils.hasText(txtDenda.getText()) 
                && StringUtils.hasText(txtMaxLamaPinjam.getText())){
            loadFormToDomain();
            Main.getMasterService().save(konfig);
            JOptionPane.showMessageDialog(Main.getMainForm(), 
                    "Konfigurasi tersimpan !");
            defaultForm();
        } else {
            JOptionPane.showMessageDialog(Main.getMainForm(), 
                    "Form tidak valid !");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        defaultForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editForm();
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtMaxLamaPinjam;
    // End of variables declaration//GEN-END:variables
}
